#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE "$MCP_DB_USER" WITH LOGIN PASSWORD '$MCP_DB_PASSWORD';
    GRANT USAGE ON SCHEMA staff, documents TO "$MCP_DB_USER";
    GRANT SELECT ON ALL TABLES IN SCHEMA staff, documents TO "$MCP_DB_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA staff, documents GRANT SELECT ON TABLES TO "$MCP_DB_USER";
EOSQL